name: iOS Build & TestFlight Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-deploy-ios:
    runs-on: macos-14  # Version plus récente
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Sync Capacitor
        run: npx cap sync ios
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      
      - name: Create Gemfile
        run: |
          cd ios/App
          cat > Gemfile << 'EOF'
          source "https://rubygems.org"
          
          gem "fastlane"
          gem "cocoapods"
          EOF
      
      - name: Install Fastlane
        run: |
          cd ios/App
          bundle install
      
      - name: Create Fastlane configuration
        run: |
          mkdir -p ios/App/fastlane
          
          # Créer Appfile
          cat > ios/App/fastlane/Appfile << 'EOF'
          app_identifier("io.winedge.app")
          team_id(ENV["APPLE_TEAM_ID"])
          EOF
          
          # Créer Fastfile
          cat > ios/App/fastlane/Fastfile << 'EOF'
          default_platform(:ios)
          
          platform :ios do
            desc "Build and upload to TestFlight"
            lane :beta do
              setup_ci
              
              # Configuration API Key
              api_key = app_store_connect_api_key(
                key_id: ENV["APP_STORE_KEY_ID"],
                issuer_id: ENV["APP_STORE_ISSUER_ID"],
                key_content: Base64.decode64(ENV["APP_STORE_P8"]),
                is_key_content_base64: false,
                in_house: false
              )
              
              # Mise à jour des pods
              cocoapods(
                clean_install: true,
                podfile: "./Podfile"
              )
              
              # Incrément du build number
              current_version = get_version_number(xcodeproj: "App.xcodeproj")
              latest_build = latest_testflight_build_number(
                api_key: api_key,
                app_identifier: "io.winedge.app",
                version: current_version
              )
              
              new_build_number = latest_build + 1
              
              increment_build_number(
                build_number: new_build_number,
                xcodeproj: "App.xcodeproj"
              )
              
              # Build de l'app
              build_app(
                scheme: "App",
                workspace: "App.xcworkspace",
                export_method: "app-store",
                configuration: "Release",
                output_directory: "./fastlane/builds",
                output_name: "WinEdge.ipa",
                clean: true,
                export_options: {
                  method: "app-store",
                  teamID: ENV["APPLE_TEAM_ID"],
                  provisioningProfiles: {},
                  signingStyle: "automatic"
                }
              )
              
              # Upload vers TestFlight
              upload_to_testflight(
                api_key: api_key,
                skip_waiting_for_build_processing: true,
                ipa: "./fastlane/builds/WinEdge.ipa"
              )
            end
          end
          EOF
      
      - name: Build and Deploy
        env:
          APP_STORE_ISSUER_ID: ${{ secrets.APP_STORE_ISSUER_ID }}
          APP_STORE_KEY_ID: ${{ secrets.APP_STORE_KEY_ID }}
          APP_STORE_P8: ${{ secrets.APP_STORE_P8 }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          cd ios/App
          bundle exec fastlane beta
      
      - name: List build outputs (debug)
        if: always()
        run: |
          echo "=== Listing ios/App contents ==="
          ls -la ios/App/
          echo "=== Listing fastlane directory ==="
          ls -la ios/App/fastlane/ || echo "No fastlane directory"
          echo "=== Looking for IPA files ==="
          find ios/App -name "*.ipa" -type f || echo "No IPA files found"
      
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: WinEdge-IPA
          path: ios/App/fastlane/builds/WinEdge.ipa
          retention-days: 30